#include<fstream>
#include<iostream>
#include<string>

using namespace std;

/*Players generally sit in a circle. The player designated to go first says the number "1", and each player thenceforth counts one number in turn. However, any number divisible by 'A' e.g. three is replaced by the word fizz and any divisible by 'B' e.g. five by the word buzz. Numbers divisible by both become fizz buzz. A player who hesitates or makes a mistake is either eliminated. 

Write a program that prints out the the pattern generated by such a scenario given the values of 'A'/'B' and 'N' which are read from an input text file. The input text file contains three space delimited numbers i.e. A, B, N. The program should then print out the final series of numbers using 'F' for fizz, 'B' for 'buzz' and 'FB' for fizz buzz
*/
void fizzbuzz( int a, int b, int N)
{
	for(int i = 1; i <= N; i++)
	{
		if( (i%a == 0) && ( i%b ==0 ))
			cout<<"FB ";
		else if( (i%a == 0))
			cout<<"F ";
		else if( (i%b == 0))
			cout<<"B ";
		else
			cout<<i<<" ";
	}

	cout<<endl;
}


int main(int argc, char* argv[])
{
	if( argc != 2)
	{
		cout<<"File name required as argument"<<endl;
		return -1;
	}

	fstream file;
	file.open(argv[1],ios::in);
	char line[25];

	while(!file.eof())
	{
		file.getline(line,25);
		string str = string(line);
		if( str.length() == 0)
			continue;
		int space_index = str.find(' ');
		int a = atoi(str.substr(0,space_index).c_str());
		str = str.substr(space_index+1);
		space_index = str.find(' ');
		int b = atoi(str.substr(0,space_index).c_str());
		str = str.substr(space_index+1);
		
		int N = atoi(str.c_str());
		

		fizzbuzz(a,b,N);
	}

	return 0;
}

